# This file stores configurations for your Shopify app.

scopes="read_orders,write_products,write_script_tags,read_content,write_content,read_themes,write_themes,read_customers,write_customers,read_orders,write_orders,read_checkouts,write_checkouts,read_locations"
